### ISSUE TITLE
Song stops playing

### ISSUE THREAD

**Issue by skgupta507** [r2hu1/MusicHub#1]
hello @r2hu1 i wanted to let u know that the playback stops when we return to homepage can the issue be fixed what do we need to change it to fix.
pls guide me through the process.

**Comment by r2hu1** [comment]
Theres a component named Player.jsx change according your need ( i can't help right now busy in a big real life project )

**Comment by skgupta507** [comment]
@r2hu1 ok bro will wait for u to push some updates in the future.
till then i will try to make some changes on my own. and test them out
